# Generated by Django 5.1.7 on 2025-04-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_bid_bidder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
    ]
